### ISSUE TITLE
Fix index error for the application configs collection

### ISSUE THREAD

**Issue by petyos** [rokwire/core-building-block#424]
We are receiving the following error when try to deploy the service on dev env.

`time="2022-02-25T05:38:49Z" level=fatal msg="Cannot start the mongoDB adapter: core-building-block/driven/storage.(*Adapter).Start() error initializing storage adapter: (CannotCreateIndex) namespace name generated from index name \"coredb.application_configs.$app_type_id_1_app_org_id_1_version.version_numbers.major_-1_version.version_numbers.minor_-1_version.version_numbers.patch_-1\" is too long (127 byte max)" service_name=core`

**Comment by shurwit** [comment]
Hi @petyos, I believe we can re-enable this index and close this issue now that we have migrated to the new dev database. Let me know if you have any concerns about re-enabling this index without changing it. Thanks!

**Comment by petyos** [comment]
Hi @shurwit! Yes, all should be good with re-enabling it.

**Comment by shurwit** [comment]
This will be re-enabled in #358
