### ISSUE TITLE
Use signature Key ID to check specific key for service account auth

### ISSUE THREAD

**Issue by shurwit** [rokwire/core-building-block#481]
Currently we are iterating through all public keys and attempting to validate the signature with each when verifying service account signatures. Instead, we should use the Key ID provided in the signature to identify the specific key to use. This should be possible after completing https://github.com/rokwire/core-auth-library-go/issues/49

**Comment by roberlander2** [comment]
The `sigauth` package does not expose `SignatureAuth.checkRequest` or `Request.getHeader`. We should consider exposing at least one of these to avoid forcing the Core BB to implement a header parsing function to read the `keyId` field since the `sigauth` package can already do this.
