### ISSUE TITLE
[FEATURE] Add description to permissions

### ISSUE THREAD

**Issue by shurwit** [rokwire/core-building-block#502]
**Is your feature request related to a problem? Please describe.**
Currently it is not always clear what the intended purpose of a permission is based on the name. This could result in confusion and incorrectly assigned permissions.

**Describe the solution you'd like**
To clarify the purpose of these permissions, we should include a `description` field (like roles/groups) that can explain what it is meant for. This should be returned to admins when they are selecting permissions to be assigned to ensure they understand the changes they are making.

**Comment by roberlander2** [comment]
This issue is being addressed by #515.
