### ISSUE TITLE
[FEATURE] manage redirect URI in OIDC provider configs

### ISSUE THREAD

**Issue by shurwit** [rokwire/core-building-block#514]
**Is your feature request related to a problem? Please describe.**
Currently the redirect URI is passed as a param to the `/login-url` and `/login` endpoints. This information could be stored in the database to avoid needing this additional data in these requests. It will also help to enforce that the client is using the proper redirect URI.

**Describe the solution you'd like**
The redirect URI should be stored in the app type configs in the OIDC identity provider.

**Comment by roberlander2** [comment]
Will be handled by a PR resolving #523.
