### ISSUE TITLE
[FEATURE] Update group roles admin API

### ISSUE THREAD

**Issue by roberlander2** [rokwire/core-building-block#517]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to grant and revoke roles included in a group using the same API.

**Describe the solution you'd like**
Add an admin API for updating group roles with a single request.

**Describe alternatives you've considered**
Using a single API for this would likely be easier to use than one API for granting roles and one for revoking them.

**Comment by shurwit** [comment]
This will be covered by #518
