### ISSUE TITLE
[BUG] Fix external system role/group synchronization

### ISSUE THREAD

**Issue by shurwit** [rokwire/core-building-block#535]
**Describe the bug**

Currently when roles/groups are set by an external system, we check for changes against the previous roles/groups in that system to determine whether to add/remove roles/groups from the account. This will mean that it will be possible for the account roles/groups to be unintentionally desynchronized from the roles/groups in the external system.

**To Reproduce**
1. Login with external auth type that contains roles that are not yet defined in the Core BB
2. Define the role in the Core BB
3. Login again
4. See that account still does not have external roles

**Expected behavior**

We should compare the external roles/groups to the account roles/groups on login to ensure that the account roles/groups always stay in sync. Only the `admin_set` flag should override this mechanism.

**Comment by roberlander2** [comment]
Will be handled by #590
