### ISSUE TITLE
[BUG] External ID synchronization

### ISSUE THREAD

**Issue by shurwit** [rokwire/core-building-block#546]
**Describe the bug**

Currently when external IDs are set by an external system, we check for changes against the previous external IDs in that system to determine whether to add/remove external IDs from the account. This will mean that it will be possible for the account external IDs to be unintentionally desynchronized from the external IDs in the external system.

**To Reproduce**
1. Login with external auth type that contains external IDs
2. Manually change external ID
3. Login again
4. See that account still has manually set external ID

**Expected behavior**

We should compare the external system external IDs to the account external IDs on login to ensure that the account external IDs always stay in sync.

**Comment by roberlander2** [comment]
Will be handled by #590
