### ISSUE TITLE
[BUG] Updating applications and organizations does not update app/orgs

### ISSUE THREAD

**Issue by shurwit** [rokwire/core-building-block#555]
**Describe the bug**

When changes are made to the applications and organizations collections, the app/orgs are not reloaded as well causing a stale cache.

**To Reproduce**
1. Change document in applications collection
2. Retrieve app/org data (eg. call `/admin/organization/applications` endpoint)
3. See stale data

**Expected behavior**

When an application or organization is changed, the app/org cache should be updated as well.

**Comment by roberlander2** [comment]
Will be handled by a PR resolving #523.
