### ISSUE TITLE
[FEATURE] Identity provider management

### ISSUE THREAD

**Issue by roberlander2** [rokwire/core-building-block#579]
**Is your feature request related to a problem? Please describe.**
There is no way to get, create, update, or delete identity providers in the current version of the Core BB.

**Describe the solution you'd like**
Add system level APIs that can be used to get, create, update, and delete identity provider documents from the database.

**Describe alternatives you've considered**
The identity providers can be managed with direct database access, but this is not good practice.

**Comment by shurwit** [comment]
This should not be necessary after #581
