### ISSUE TITLE
[TASK] Clean up unused doc resources/schemas

### ISSUE THREAD

**Issue by shurwit** [rokwire/core-building-block#593]
### Description
Currently there are many resources and schemas defined in the docs that are unused. These will lead to confusion and clutter. Models with circular dependencies also cause errors on the latest version of the Swagger libraries we are using. These models should be removed or updated to avoid this whenever possible.

### Acceptance Criteria
- [ ] All unused resources/schemas defined in the docs have been removed
- [ ] All dependencies have been upgraded to the latest versions

**Comment by roberlander2** [comment]
This will be handled by #624
